spring.application.name=democollege

spring.datasource.url=jdbc:mysql://localhost:3306/college_db
spring.datasource.username=mayank
spring.datasource.password=kill.end0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true